const Constants = {
  USER_SIGNING_IN: 'USER_SIGNING_IN',
  USER_SIGNED_IN: 'USER_SIGNED_IN',
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_SOCKET: 'SET_SOCKET',
  USER_SIGNED_OUT: 'USER_SIGNED_OUT',
  USER_SIGNING_OUT: 'USER_SIGNING_OUT',
  SESSIONS_ERROR: 'SESSIONS_ERROR',
  USER_REGISTERING: 'USER_REGISTERING',
  USER_REGISTERED: 'USER_REGISTERED',
  REGISTRATIONS_ERROR: 'REGISTRATIONS_ERROR',
};

export default Constants;
